[DEV-2518] Transaction event sift
DFXswiss/api pull request #1336
Opened 2024-05-31 07:42 UTC by Kolibri1990

### Release Checklist

#### Pre-Release

- [ ] Check migrations
  - No database related infos (sqldb-xxx)
  - Impact on GS (new/removed columns)
- [ ] Check for linter errors (in PR)
- [ ] Test basic user operations (on [DFX services](https://dev.services.dfx.swiss))
  - Login/logout
  - Buy/sell payment request
  - KYC page

#### Post-Release

- Test basic user operations
- Monitor application insights log

2024-05-31 16:55 UTC, Yannick1712 commented on src/integration/sift/services/sift.service.ts
> +    }
Could be in an entity method in bankTx/checkoutTx entity

2024-05-31 16:55 UTC, Yannick1712 commented on src/integration/sift/services/sift.service.ts
> +      $amount: entity.inputAmount * 10000,
Maybe comment the line why 10000 Multiplier is needed

2024-06-03 06:45 UTC, davidleomay approved these changes

2024-06-11 14:56 UTC, davidleomay commented on src/subdomains/supporting/fiat-payin/services/fiat-payin-sync.service.ts
> +        if (checkoutTx.authStatusReason && buy) await this.siftService.transactionCheckoutDeclined(checkoutTx, buy);
Put into an `else`?

2024-06-11 14:56 UTC, davidleomay commented on src/integration/sift/services/sift.service.ts
> +      ],
Maybe this can be done with a helper method (and reused above)?

2024-06-11 14:56 UTC, davidleomay commented on src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
>        } catch (e) {
Add decline category (for all transaction events)?

2024-06-11 19:35 UTC, davidleomay commented on src/subdomains/supporting/fiat-payin/services/fiat-payin-sync.service.ts
> +        }
Only if `checkoutTx.authStatusReason`?

2024-06-11 19:35 UTC, davidleomay commented on src/subdomains/supporting/payment/entities/transaction-request.entity.ts
> +  siftScore: string;
Maybe we should call it `siftResponse? (also for BuyCrypto)

2024-06-14 00:05 UTC, davidleomay requested changes

2024-06-14 00:05 UTC, davidleomay commented on migration/1718094174304-addAuthStatus.js
Remove this migration

2024-06-14 12:10 UTC, davidleomay approved these changes

2024-06-15 13:32 UTC, merged